tab_spaces=3
use_field_init_shorthand=true
fn_args_layout="Compressed"
use_small_heuristics="Max"
use_try_shorthand=true
max_width=110

#unstable_features=true
#blank_lines_lower_bound=0
#blank_lines_upper_bound=2
#wrap_comments=true
#comment_width=100
#condense_wildcard_suffixes=true
#control_brace_style="ClosingNextLine"
#fn_single_line=true
#format_code_in_doc_comments=true
#format_strings=true
#match_arm_blocks=false
#merge_imports=true
#normalize_doc_attributes=true
#overflow_delimited_expr=true
#reorder_impl_items=true
#struct_field_align_threshold=20
#enum_discrim_align_threshold=20
#where_single_line=true


